import js from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';
import { defineConfig } from 'eslint/config';

export default defineConfig([
  {
    name: 'forvais/plugin/@eslint/js',
    plugins: {
      js,
    },
    rules: {
      'accessor-pairs': 'error',
      'array-callback-return': 'error',
      'arrow-body-style': ['error', 'as-needed'],
      'block-scoped-var': 'error',
      'camelcase': 'error',
      'capitalized-comments': 'off',
      'class-methods-use-this': ['error', {
        ignoreOverrideMethods: true,
        ignoreClassesWithImplements: 'all',
      }],
      'complexity': 'error',
      'consistent-return': 'error',
      'consistent-this': 'error',
      'constructor-super': 'error',
      'curly': ['error', 'multi-line'],
      'default-case': 'error',
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-notation': 'error',
      'eqeqeq': 'error',
      'for-direction': 'error',
      'func-name-matching': ['error', 'always'],
      'func-names': ['error', 'always'],
      'func-style': 'off',
      'getter-return': 'error',
      'grouped-accessor-pairs': 'off',
      'guard-for-in': 'error',
      'id-denylist': 'off',
      'id-length': 'off',
      'id-match': 'off',
      'init-declarations': 'off',
      'logical-assignment-operators': 'off',
      'max-classes-per-file': 'off',
      'max-depth': ['error', 3],
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-nested-callbacks': 'error',
      'max-params': 'off',
      'max-statements': 'off',
      'new-cap': 'error',
      'no-alert': 'error',
      'no-array-constructor': 'error',
      'no-async-promise-executor': 'error',
      'no-await-in-loop': 'error',
      'no-bitwise': 'off',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-console': 'off',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-constructor-return': 'error',
      'no-continue': 'off',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-div-regex': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-duplicate-imports': 'error',
      'no-else-return': 'error',
      'no-empty': 'off',
      'no-empty-character-class': 'error',
      'no-empty-function': 'off',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-ex-assign': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-boolean-cast': 'error',
      'no-extra-label': 'error',
      'no-fallthrough': ['error', {
        commentPattern: 'falls?',
      }],
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-implicit-coercion': ['error', {
        boolean: false,
        number: true,
        string: true,
        allow: ['!!'],
      }],
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-import-assign': 'error',
      'no-inline-comments': 'off',
      'no-inner-declarations': 'error',
      'no-invalid-regexp': 'error',
      'no-invalid-this': 'error',
      'no-irregular-whitespace': 'error',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-lonely-if': 'error',
      'no-loop-func': 'error',
      'no-loss-of-precision': 'error',
      'no-magic-numbers': 'off',
      'no-misleading-character-class': 'error',
      'no-multi-assign': 'error',
      'no-multi-str': 'error',
      'no-negated-condition': 'off',
      'no-nested-ternary': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-new-wrappers': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-object-constructor': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': 'error',
      'no-plusplus': 'off',
      'no-promise-executor-return': 'error',
      'no-proto': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'warn',
      'no-restricted-exports': 'off',
      'no-restricted-globals': 'off',
      'no-restricted-imports': 'off',
      'no-restricted-properties': 'error',
      'no-restricted-syntax': 'off',
      'no-return-assign': ['error', 'always'],
      'no-script-url': 'error',
      'no-self-assign': ['warn', {
        props: true,
      }],
      'no-self-compare': 'warn',
      'no-sequences': 'error',
      'no-setter-return': 'warn',
      'no-shadow': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'error',
      'no-ternary': 'off',
      'no-this-before-super': 'error',
      'no-throw-literal': 'error',
      'no-unassigned-vars': 'error',
      'no-undef': 'error',
      'no-undef-init': 'error',
      'no-undefined': 'off',
      'no-underscore-dangle': 'off',
      'no-unexpected-multiline': 'error',
      'no-unmodified-loop-condition': 'warn',
      'no-unneeded-ternary': 'error',
      'no-unreachable': 'error',
      'no-unreachable-loop': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-expressions': ['error', {
        allowShortCircuit: false,
        allowTernary: false,
        allowTaggedTemplates: false,
      }],
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'warn',
      'no-unused-vars': ['error', {
        vars: 'all',
        args: 'after-used',
        ignoreRestSiblings: true,
      }],
      'no-use-before-define': 'error',
      'no-useless-assignment': 'warn',
      'no-useless-backreference': 'off',
      'no-useless-call': 'error',
      'no-useless-catch': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': 'error',
      'no-useless-escape': 'error',
      'no-useless-rename': ['error', {
        ignoreDestructuring: false,
        ignoreImport: false,
        ignoreExport: false,
      }],
      'no-useless-return': 'error',
      'no-var': 'error',
      'no-void': 'error',
      'no-warning-comments': ['off', {
        terms: ['todo', 'fixme', 'xxx'],
        location: 'start',
      }],
      'no-with': 'error',
      'object-shorthand': 'error',
      'one-var': 'off',
      'operator-assignment': ['error', 'always'],
      'prefer-arrow-callback': 'error',
      'prefer-const': 'error',
      'prefer-destructuring': ['error', {
        VariableDeclarator: {
          array: false,
          object: true,
        },
      }],
      'prefer-exponentiation-operator': 'off',
      'prefer-named-capture-group': 'error',
      'prefer-numeric-literals': 'error',
      'prefer-object-has-own': 'error',
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': ['error', {
        allowEmptyReject: true,
      }],
      'prefer-regex-literals': 'off',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'preserve-caught-error': 'error',
      'radix': 'error',
      'require-atomic-updates': 'error',
      'require-await': 'off',
      'require-unicode-regexp': 'off',
      'require-yield': 'error',
      'sort-imports': 'off',
      'sort-keys': 'off',
      'sort-vars': 'off',
      'strict': 'error',
      'symbol-description': 'error',
      'unicode-bom': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'vars-on-top': 'error',
      'yoda': 'error',
    },
  },
  {
    name: 'forvais/plugin/stylistic/eslint-plugin',
    plugins: {
      stylistic,
    },
    rules: {
      'stylistic/array-bracket-newline': 'off',
      'stylistic/array-bracket-spacing': ['error', 'never'],
      'stylistic/array-element-newline': ['error', 'consistent'],
      'stylistic/arrow-parens': ['error', 'as-needed'],
      'stylistic/arrow-spacing': ['error', {
        before: true,
        after: true,
      }],
      'stylistic/block-spacing': ['error', 'always'],
      'stylistic/brace-style': ['error', 'stroustrup'],
      'stylistic/comma-dangle': ['error', 'always-multiline'],
      'stylistic/comma-spacing': ['error', { 'before': false, 'after': true }],
      'stylistic/comma-style': 'error',
      'stylistic/computed-property-spacing': 'error',
      'stylistic/curly-newline': 'error',
      'stylistic/dot-location': ['error', 'property'],
      'stylistic/eol-last': 'error',
      'stylistic/function-call-argument-newline': ['error', 'consistent'],
      'stylistic/function-call-spacing': ['error', 'never'],
      'stylistic/function-paren-newline': ['error', 'consistent'],
      'stylistic/generator-star-spacing': 'error',
      'stylistic/implicit-arrow-linebreak': ['error', 'beside'],
      'stylistic/indent': ['error', 3, {
        SwitchCase: 1,
      }],
      'stylistic/indent-binary-ops': ['error', 2],
      'stylistic/jsx-child-element-spacing': ['off'],
      'stylistic/jsx-closing-bracket-location': ['error', 'tag-aligned'],
      'stylistic/jsx-closing-tag-location': 'off', // Conflicts with 'stylistic/function-paren-newline'
      'stylistic/jsx-curly-brace-presence': ['error'],
      'stylistic/jsx-curly-newline': ['error', {
        multiline: 'require',
        singleline: 'forbid',
      }],
      'stylistic/jsx-curly-spacing': ['error'],
      'stylistic/jsx-equals-spacing': ['error', 'never'],
      'stylistic/jsx-first-prop-new-line': ['error', 'multiline-multiprop'],
      'stylistic/jsx-function-call-newline': 'off',
      'stylistic/jsx-indent-props': ['error', 2],
      'stylistic/jsx-max-props-per-line': ['error', { when: 'multiline' }],
      'stylistic/jsx-newline': ['error', { 'prevent': true, 'allowMultilines': true }],
      'stylistic/jsx-one-expression-per-line': ['error', { allow: 'single-line' }],
      'stylistic/jsx-pascal-case': ['error'],
      'stylistic/jsx-quotes': ['error', 'prefer-double'],
      'stylistic/jsx-self-closing-comp': ['error'],
      'stylistic/jsx-tag-spacing': ['error', {
        closingSlash: 'never',
        beforeSelfClosing: 'always',
        afterOpening: 'never',
        beforeClosing: 'never',
      }],
      'stylistic/jsx-wrap-multilines': ['error'],
      'stylistic/key-spacing': ['error', {
        beforeColon: false,
        afterColon: true,
        mode: 'strict',
      }],
      'stylistic/keyword-spacing': ['error', {
        before: true,
        after: true,
        overrides: {
          return: { after: true },
          throw: { after: true },
          case: { after: true },
        },
      }],
      'stylistic/line-comment-position': 'off',
      'stylistic/linebreak-style': ['error', 'unix'],
      'stylistic/lines-around-comment': 'off',
      'stylistic/lines-between-class-members': ['error', 'always', {
        exceptAfterSingleLine: true,
      }],
      'stylistic/max-statements-per-line': 'off',
      'stylistic/member-delimiter-style': ['error', {
        multiline: {
          delimiter: 'comma',
          requireLast: true,
        },
        singleline: {
          delimiter: 'comma',
          requireLast: false,
        },
        multilineDetection: 'brackets',
      }],
      'stylistic/multiline-comment-style': 'off',
      'stylistic/multiline-ternary': 'off',
      'stylistic/new-parens': 'error',
      'stylistic/newline-per-chained-call': 'off',
      'stylistic/max-len': ['off', 120],
      'stylistic/no-confusing-arrow': 'error',
      'stylistic/no-extra-parens': 'off',
      'stylistic/no-extra-semi': 'error',
      'stylistic/no-floating-decimal': 'error',
      'stylistic/no-mixed-operators': ['error', {
        groups: [
          ['%', '**'],
          ['%', '+'],
          ['%', '-'],
          ['%', '*'],
          ['%', '/'],
          ['**', '+'],
          ['**', '-'],
          ['**', '*'],
          ['**', '/'],
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof'],
        ],
        allowSamePrecedence: false,
      }],
      'stylistic/no-mixed-spaces-and-tabs': 'error',
      'stylistic/no-multi-spaces': ['error', {
        ignoreEOLComments: true,
        exceptions: {
          VariableDeclarator: true,
          Property: true,
        },
      }],
      'stylistic/no-multiple-empty-lines': 'error',
      'stylistic/no-tabs': 'error',
      'stylistic/no-trailing-spaces': ['error', {
        skipBlankLines: true,
        ignoreComments: false,
      }],
      'stylistic/no-whitespace-before-property': 'error',
      'stylistic/nonblock-statement-body-position': ['error', 'beside'],
      'stylistic/object-curly-newline': ['error', {
        multiline: true,
        consistent: true,
      }],
      'stylistic/object-curly-spacing': ['error', 'always'],
      'stylistic/object-property-newline': ['error', {
        allowAllPropertiesOnSameLine: true,
      }],
      'stylistic/one-var-declaration-per-line': 'error',
      'stylistic/operator-linebreak': 'error',
      'stylistic/padded-blocks': ['error', 'never'],
      'stylistic/padding-line-between-statements': 'error',
      'stylistic/quote-props': ['error', 'consistent'],
      'stylistic/quotes': ['error', 'single', { avoidEscape: true }],
      'stylistic/rest-spread-spacing': 'error',
      'stylistic/semi': 'error',
      'stylistic/semi-spacing': 'error',
      'stylistic/semi-style': 'error',
      'stylistic/space-before-blocks': 'error',
      'stylistic/space-before-function-paren': 'off',
      'stylistic/space-in-parens': 'error',
      'stylistic/space-infix-ops': 'error',
      'stylistic/space-unary-ops': 'error',
      'stylistic/spaced-comment': 'error',
      'stylistic/switch-colon-spacing': 'error',
      'stylistic/template-curly-spacing': 'error',
      'stylistic/template-tag-spacing': 'error',
      'stylistic/type-annotation-spacing': ['error'],
      'stylistic/type-generic-spacing': ['error'],
      'stylistic/type-named-tuple-spacing': ['error'],
      'stylistic/wrap-iife': ['error', 'inside'],
      'stylistic/wrap-regex': 'error',
      'stylistic/yield-star-spacing': ['error', 'before'],
    },
  },
]);
