name: node-ci:javascript

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/javascript/**'

jobs:
  node-ci:
    uses: ./.github/workflows/node-ci.yml
    secrets: inherit
    with:
      root: ./packages/javascript
