name: node-ci:javascript

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/javascript/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./.github/workflows/node-ci.yml
        with:
          root: ./packages/javascript
