name: node-ci:typescript

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/typescript/**'

jobs:
  node-ci:
    uses: ./.github/workflows/node-ci.yml
    secrets: inherit
    with:
      project: "@forvais/eslint-config-typescript-c5d52589"
