name: node-ci

on:
  workflow_call:
    inputs:
      packageJson: # Relative path from repository root to package/app package.json
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Derive project metadata
        shell: bash
        run: |
          PROJECT_ROOT="$(dirname "${{ inputs.packageJson }}")"
          PACKAGE_NAME="$(node -p "require('./${{ inputs.packageJson }}').name")"

          echo "root=$PROJECT_ROOT" >> "$GITHUB_ENV"
          echo "packageName=$PACKAGE_NAME" >> "$GITHUB_ENV"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml
            ${{ env.projectRoot }}/package.json

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: npx --no-install turbo --filter=${{ env.packageName }} lint
