name: release-please CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # v6
        with:
          persist-credentials: false

      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          node-version: 24.x

      - name: Extract package name
        id: pkg
        run: |
          BRANCH="${{ github.head_ref }}"
          PKG="${BRANCH##*--}"
          echo "name=$PKG" >> $GITHUB_OUTPUT

      - run: pnpm --filter "${{ steps.pkg.outputs.name }}" lint
