name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      javascript--tag_name: ${{ steps.release.outputs.javascript--tag_name }}
      javascript--release_created: ${{ steps.release.outputs.javascript--release_created }}
      typescript--tag_name: ${{ steps.release.outputs.typescript--tag_name }}
      typescript--release_created: ${{ steps.release.outputs.typescript--release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"

  release-javascript:
    if: ${{ needs.release-please.outputs.javascript--release_created }}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - name: publish
        uses: ./.github/workflows/release-npmjs.yml
        with:
          root: ./packages/typescript

  release-typescript:
    if: ${{ needs.release-please.outputs.typescript--release_created }}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - name: publish
        uses: ./.github/workflows/release-npmjs.yml
        with:
          root: ./packages/typescript
